theme: jekyll-theme-giellalt
title: Dictionary for Udmurt ⇒ Finnish
description: An electronic dictionary from Udmurt to Finnish

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
